#!/usr/bin/env python3
"""Wire Jetty's LIVE duplex voice (ElevenLabs Agents, custom-LLM = this server).

What it does:
 1. Reads config.json (elevenlabs.api_key + voice_id) and jetty-duplex.json (bearer token).
 2. Stores the bearer token as an ElevenLabs workspace secret.
 3. Creates (or updates) an ElevenLabs Agent whose LLM is THIS server's
    /v1/chat/completions on port 4722 — so the brain stays Claude + your vault RAG
    + long-term memory, and ElevenLabs only does ears/mouth/turn-taking.
 4. Saves agent_id into jetty-duplex.json; the 📡 button in the viewer then works.

Prereqs:
 - An ElevenLabs API key WITH Agents (Conversational AI) permission in config.json.
   (The old TTS-only key returns 401 here — when you rotate the exposed key, tick
   the Agents scope on the new one.)
 - A PUBLIC https URL that forwards to localhost:4722 (ElevenLabs' cloud must reach
   the brain). Easiest today:  ./bin/cloudflared tunnel --url http://localhost:4722
   (prints a https://….trycloudflare.com URL — pass it with --url).
   Long-term: Tailscale Funnel (see integrations/TAILSCALE.md).

Usage:
  python3 setup_duplex.py --url https://your-tunnel-host   [--name "Jetty"]
"""
import argparse
import json
import os
import sys
import urllib.error
import urllib.request

ROOT = os.path.dirname(os.path.abspath(__file__))
EL = "https://api.elevenlabs.io"


def req(path, key, data=None, method=None):
    body = json.dumps(data).encode() if data is not None else None
    r = urllib.request.Request(EL + path, data=body,
                               headers={"xi-api-key": key, "Content-Type": "application/json"},
                               method=method or ("POST" if body else "GET"))
    try:
        with urllib.request.urlopen(r, timeout=30) as resp:
            return json.load(resp), None
    except urllib.error.HTTPError as e:
        return None, f"{e.code}: {e.read().decode(errors='ignore')[:400]}"
    except Exception as e:
        return None, str(e)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", required=True, help="public https base URL that forwards to localhost:4722")
    ap.add_argument("--name", default="Jetty (Second Brain)")
    args = ap.parse_args()
    base = args.url.rstrip("/")

    cfg = json.load(open(os.path.join(ROOT, "config.json")))
    el = cfg.get("elevenlabs") or {}
    key, voice = el.get("api_key", ""), el.get("voice_id", "")
    if not key or key.startswith("PUT-"):
        sys.exit("config.json has no ElevenLabs api_key.")

    dxp = os.path.join(ROOT, "jetty-duplex.json")
    dx = json.load(open(dxp)) if os.path.exists(dxp) else {}
    token = dx.get("token")
    if not token:
        sys.exit("jetty-duplex.json has no token — start server.py once first.")

    # 1) store the bearer token as a workspace secret (idempotent-ish: new name per run is fine)
    sec, err = req("/v1/convai/secrets", key, {"type": "new", "name": "jetty-brain-token", "value": token})
    if err and "already" in err.lower():
        secs, lerr = req("/v1/convai/secrets", key)
        sec = next((s for s in (secs or {}).get("secrets", [])
                    if s.get("name") == "jetty-brain-token"), None) if not lerr else None
        err = None if sec else (lerr or "secret exists but could not be fetched")
    if err or not sec:
        sys.exit(f"Could not store the token secret: {err}\n"
                 "→ Most likely the API key lacks the Agents/Convai scope.")
    secret_id = sec.get("secret_id") or sec.get("id")

    agent_cfg = {
        "name": args.name,
        "conversation_config": {
            "agent": {
                "first_message": "Online, sir. What do you need?",
                "language": "en",
                "prompt": {
                    "prompt": ("You are JETTY. Your replies are generated by a custom LLM (the user's "
                               "own second-brain server) — pass everything through faithfully."),
                    "llm": "custom-llm",
                    "custom_llm": {
                        "url": base,
                        "model_id": "jetty-brain",
                        "api_key": {"secret_id": secret_id},
                    },
                },
            },
            "tts": {"voice_id": voice, "model_id": "eleven_flash_v2_5"},
            "asr": {"quality": "high"},
        },
    }

    agent_id = dx.get("agent_id")
    if agent_id:
        res, err = req(f"/v1/convai/agents/{agent_id}", key, agent_cfg, method="PATCH")
        action = "updated"
    else:
        res, err = req("/v1/convai/agents/create", key, agent_cfg)
        action = "created"
        agent_id = (res or {}).get("agent_id")
    if err or not agent_id:
        sys.exit(f"Agent {action} failed: {err}\nRaw config sent:\n" + json.dumps(agent_cfg, indent=2))

    dx["agent_id"] = agent_id
    dx["custom_llm_url"] = base
    with open(dxp, "w") as f:
        json.dump(dx, f, indent=1)
    print(f"Agent {action}: {agent_id}")
    print(f"Custom LLM: {base}  →  localhost:4722 (Bearer token via workspace secret)")
    print("Restart nothing — press the 📡 button in the viewer and start talking.")


if __name__ == "__main__":
    main()
